codecov:
  require_ci_to_pass: true
  branch: main
  notify:
    wait_for_ci: true
    after_n_builds: 3

coverage:
  precision: 2
  round: nearest
  range: "80...100"
  status:
    patch: true
    project:
      default:
        target: auto
        threshold: 1%

flag_management:
  default_rules: # the rules that will be followed for any flag added, generally
    carryforward: false
    statuses:
      - name_prefix: "spark-"
        type: project
        target: auto
        threshold: 1%

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files,footer"  # if true: only post the comment if coverage changes
  behavior: default
  require_changes: false
  after_n_builds: 3
