codecov:
  require_ci_to_pass: true
  branch: main

coverage:
  precision: 2
  round: nearest
  range: "80...100"
  status:
    patch: true
    project:
      default:
        target: auto
        threshold: 1%

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files,footer"  # if true: only post the comment if coverage changes
  behavior: default
  require_changes: false
