name: "Publish documentation 📑"
description: "Generate and publish documentation"

inputs:
  token:
    description: 'A Github PAT'
    required: true
runs:
  using: "composite"
  steps:
    # BUILD MDOC, sbt should take the latest version
    - name: Build the microsite 💻
      run: sbt docs/mdoc
      shell: bash

    # DOWNLOAD DOCS, this will download all the artifacts because no name provided
    - name: Download docs ⬇️
      uses: actions/download-artifact@v3
      with:
        path: "docs/target/mdoc/docs/api/"

    - name: Debug
      run: |
        ls -l docs/target/mdoc/docs/api/
        find docs/target/mdoc/docs/api/ -maxdepth 4 -type d -exec ls -ld "{}" \;
      shell: bash

    # DEPLOY TO GITHUB PAGES
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4.4.1
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: docs/target/mdoc # The folder the action should deploy.
        token: ${{ inputs.token }}
