name: CI
on:
  pull_request:
    branches-ignore:
      - gh-pages
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  todo-check:
    runs-on: ubuntu-20.04
    steps:
      - name: Code Todo Bot
        uses: bilalshaikh42/todo@v0.0.1
