name: CI
on:
  pull_request:
    branches-ignore:
      - gh-pages
  workflow_dispatch:

jobs:
  build:
    #if: github.event.pull_request.draft == false
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: olafurpg/setup-scala@v13
      - name: Coursier cache
        uses: coursier/cache-action@v6
      - name: Code & Doc changes filter
        uses: dorny/paths-filter@v2.10.2
        with:
          filters: |
            core:
              - 'core/src/**'
            doc:
              - 'docs/**'
      - name: Code Format
        if: steps.changes.outputs.core == 'true'
        run: sbt scalafmtCheckAll
      - name: Test & coverage
        if: steps.changes.outputs.core == 'true'
        run: sbt coverage core/test coverageReport coverageAggregate
      - uses: codecov/codecov-action@v2
        if: steps.changes.outputs.core == 'true'
        with:
          files: ./target/scala-2.12/scoverage-report/scoverage.xml
          fail_ci_if_error: true
          verbose: false
      - name: Check the microsite
        if: steps.changes.outputs.core == 'true' || steps.changes.outputs.doc == 'true'
        run: sbt docs/mdoc
      - name: Check the scaladocs
        if: steps.changes.outputs.core == 'true' || steps.changes.outputs.doc == 'true'
        run: sbt core/doc
      - name: Cleaning for cache
        run: |
          rm -rf "$HOME/.ivy2/local" || true
          find $HOME/Library/Caches/Coursier/v1        -name "ivydata-*.properties" -delete || true
          find $HOME/.ivy2/cache                       -name "ivydata-*.properties" -delete || true
          find $HOME/.cache/coursier/v1                -name "ivydata-*.properties" -delete || true
          find $HOME/.sbt                              -name "*.lock"               -delete || true
