name: CI
on:
  pull_request:
    branches-ignore:
      - gh-pages
  workflow_dispatch:

jobs:
  build:
    #if: github.event.pull_request.draft == false
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Check, build and doc 🎯
        uses: ./.github/actions/check_build_and_doc
      - name: Cleaning for cache 🚯
        uses: ./.github/actions/clean_cache
