name: Update Dependency Graph

on:
  push:
    branches:
      - main

jobs:
  update-graph:
    if: github.repository == 'hablapps/doric'
    name: Update Dependency Graph
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
      - uses: scalacenter/sbt-dependency-submission@v2.1.0
