name: "Pull Request target"
on:
  - pull_request_target

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v4
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          sync-labels: true
  todo-comments:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Create Todo Comments
        uses: eruizalo/github-action-todo-commenter@feat/pull_request_target
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          ignore-pattern: '.js$|.snap$'
          review-message: "Please take a look :eyes:"
          tags: "TODO,@todo"
