name: Publish temp site

on:
  push:
    #    branches:
    #      - '*doc/*'
    branches-ignore:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  context_dump:
    runs-on: ubuntu-latest
    steps:
      - name: <DEBUG> Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
        shell: bash
  publish-doc:
    uses: ./.github/workflows/wc_publishSite.yml
#    with:
#      scope: "uploadDoc"
