name: Publish temp site

on:
  push:
#    branches:
#      - '*doc/*'
    branches-ignore:
      - main
      - fix/coverage_twice # TODO if you see this, tell me
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish-doc:
    uses: ./.github/workflows/wc_publishSite.yml
    with:
      scope: "uploadDoc"
