name: Release

on:
  push:
    branches: [main]
    tags: ["*"]

jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Check, build and doc 🎯
        uses: ./.github/actions/check_build_and_doc
      - name: Publish documentation 📑
        uses: ./.github/actions/publish_doc
      - name: Maven release 🎁
        run: sbt ci-release
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
      - name: Cleaning for cache 🚯
        uses: ./.github/actions/clean_cache
